import { converter, formatHex } from "culori";
import { writeFileSync } from "node:fs";

const toRgb = converter("rgb");
const hex = (l, c, h) => formatHex(toRgb({ mode: "oklch", l, c, h }));

// [name, L, C, H] — from guardian-aura-pro/src/styles.css :root
const COLOR_TOKENS = [
  ["background", 1, 0, 0],
  ["foreground", 0.211, 0.0206, 268.1],
  ["card", 1, 0, 0],
  ["cardForeground", 0.211, 0.0206, 268.1],
  ["popover", 1, 0, 0],
  ["popoverForeground", 0.211, 0.0206, 268.1],
  ["primary", 0.5854, 0.2041, 277.12],
  ["primaryForeground", 1, 0, 0],
  ["secondary", 0.9761, 0.0071, 264.54],
  ["secondaryForeground", 0.211, 0.0206, 268.1],
  ["muted", 0.9761, 0.0071, 264.54],
  ["mutedForeground", 0.5513, 0.0234, 264.36],
  ["accent", 0.6559, 0.2118, 354.31],
  ["accentForeground", 1, 0, 0],
  ["destructive", 0.6368, 0.2078, 25.33],
  ["destructiveForeground", 0.984, 0.003, 247.858],
  ["border", 0.9219, 0.0074, 264.53],
  ["input", 0.9219, 0.0074, 264.53],
  ["ring", 0.5854, 0.2041, 277.12],
  ["brandBlue", 0.6231, 0.188, 259.81],
  ["brandIndigo", 0.5854, 0.2041, 277.12],
  ["brandViolet", 0.6056, 0.2189, 292.72],
  ["brandPink", 0.6559, 0.2118, 354.31],
  ["emergency", 0.6368, 0.2078, 25.33],
  ["emergencyForeground", 1, 0, 0],
  ["success", 0.7227, 0.192, 149.58],
  ["successForeground", 1, 0, 0],
  ["warning", 0.7686, 0.1647, 70.08],
  ["warningForeground", 1, 0, 0],
  ["surface", 0.9842, 0.0034, 247.86],
];

const colors = Object.fromEntries(COLOR_TOKENS.map(([name, l, c, h]) => [name, hex(l, c, h)]));

// --radius: 1rem (16px); radius-<size> = 16 + offset, per styles.css @theme block
const BASE_RADIUS = 16;
const radii = {
  sm: BASE_RADIUS - 4,
  md: BASE_RADIUS - 2,
  lg: BASE_RADIUS,
  xl: BASE_RADIUS + 4,
  xl2: BASE_RADIUS + 8,
  xl3: BASE_RADIUS + 12,
  xl4: BASE_RADIUS + 16,
};

const gradientBrand = [colors.brandBlue, colors.brandIndigo, colors.brandViolet, colors.brandPink];

const out = `// GENERATED by scripts/generate-tokens.mjs — do not edit by hand.
// Source: guardian-aura-pro/src/styles.css (:root block, light theme only).

export const colors = ${JSON.stringify(colors, null, 2)} as const;

export const radii = ${JSON.stringify(radii, null, 2)} as const;

export const gradientBrand = ${JSON.stringify(gradientBrand, null, 2)} as const;
`;

writeFileSync(new URL("../src/theme/tokens.ts", import.meta.url), out);
console.log("Wrote src/theme/tokens.ts");
