// GENERATED by scripts/generate-tokens.mjs — do not edit by hand.
// Source: guardian-aura-pro/src/styles.css (:root block, light theme only).

export const colors = {
  "background": "#ffffff",
  "foreground": "#141822",
  "card": "#ffffff",
  "cardForeground": "#141822",
  "popover": "#ffffff",
  "popoverForeground": "#141822",
  "primary": "#6366f1",
  "primaryForeground": "#ffffff",
  "secondary": "#f5f7fc",
  "secondaryForeground": "#141822",
  "muted": "#f5f7fc",
  "mutedForeground": "#6b7280",
  "accent": "#ec4899",
  "accentForeground": "#ffffff",
  "destructive": "#ef4444",
  "destructiveForeground": "#f8fafc",
  "border": "#e3e5ea",
  "input": "#e3e5ea",
  "ring": "#6366f1",
  "brandBlue": "#3b82f6",
  "brandIndigo": "#6366f1",
  "brandViolet": "#8b5cf6",
  "brandPink": "#ec4899",
  "emergency": "#ef4444",
  "emergencyForeground": "#ffffff",
  "success": "#22c55e",
  "successForeground": "#ffffff",
  "warning": "#f59e0b",
  "warningForeground": "#ffffff",
  "surface": "#f8fafc"
} as const;

export const radii = {
  "sm": 12,
  "md": 14,
  "lg": 16,
  "xl": 20,
  "xl2": 24,
  "xl3": 28,
  "xl4": 32
} as const;

export const gradientBrand = [
  "#3b82f6",
  "#6366f1",
  "#8b5cf6",
  "#ec4899"
] as const;
